### ISSUE TITLE
Receiving state from an Object

### ISSUE THREAD

**Issue by alexlafroscia** [microstates/microstates.js#262] opened 2018-10-31 23:56 UTC
I'm playing around with Microstates and am trying something pretty basic to state:

```javascript
import { create } from 'microstates';

const ms = create(Object, {
  foo: 'bar'
});
```

I'm expecting that `ms.state` would be `{ foo: 'bar' }` but it's `undefined`... is that the desired behavior or a bug?

`ms.foo.state` is indeed `'bar'` as I would expect but the top-level object doesn't produce what the README seems to indicate it would.

**Note:** This was observed against version `0.11.0`

**Comment by alexlafroscia** [comment] 2018-11-01 00:05
It seems like the behavior with primitives is as I would expect:

```javascript
create(Number, 42).state; // 42
```

**Comment by taras** [comment] 2018-11-01 00:49
Object and Array not having `state` is expected behaviour as last version of microstates. You can read about it in the #227. We made this change because it's not possible to compute state lazily on objects and arrays without proxy. There is a lot of details about it in the PR.

In practice, it's not very useful to call `state` on the composed objects. Referencing specific microstates makes it possible for us to make everything lazy. If you really need the state of the entire object, you can do this.

```js
import { create, valueOf } from 'microstates';

const ms = create(Object, {
  foo: 'bar'
});

valueOf(ms);
``` 

Let me know if you have more questions. I'll close this issue.

**Closed by taras** 2018-11-01 00:49 UTC
Labels: triage

**Comment by alexlafroscia** [comment] 2018-11-01 01:54
That makes sense -- you should just remove those examples from your README then, because there's a bunch of examples on there that don't actually work!

**Comment by alexlafroscia** [comment] 2018-11-01 01:59
Just from the outside perspective, this behavior is really troll-y:

> before:
> 
> ```javascript
> let array = create([], [1, 2, 3])
> array[0].state //=> 1
> array[2].state //=> 1
> ```
> 
> after:
> 
> ```javascript
> let array = create([], [1, 2, 3])
> for (item of array) {
>   console.log(item.state)
> }
> // logs 1 2 3
> ```

On a recent podcast I heard mention of the fact that it is "just JavaScript" (or feels that way) but this kind of behavior is a major "gotcha". At least from my perspective, it is really unexpected to have an Array-like object that I can't index into!

**Comment by taras** [comment] 2018-11-01 02:17
> you should just remove those examples from your README then

We did this in last release, maybe we missed some? Can you show me which one?

> On a recent podcast I heard mention of the fact that it is "just JavaScript" (or feels that way) but this kind of behavior is a major "gotcha". At least from my perspective, it is really unexpected to have an Array-like object that I can't index into!

`create([], [1. 2, 3])` returns an iterable. If you need to access the objects via an index, then you can `let array = [...create([], [1, 2, 3])]`. 

I agree that it's not ideal, but with JavaScript we're constantly forced to make compromises. We can make it convenient but not lazy (unless we introduce proxies). If we want laziness then Iterables are the most JavaScript way to make things lazy. It's also most likely to improve in performance over time.

Again, I wish we didn't have to do this but we really don't have a lot of options.

**Comment by cowboyd** [comment] 2018-11-01 04:48
I'd like to echo @taras's comment.

>On a recent podcast I heard mention of the fact that it is "just JavaScript" (or feels that way) but this kind of behavior is a major "gotcha". At least from my perspective, it is really unexpected to have an Array-like object that I can't index into!

This really is the most JavaScript solution out there, it's just _less_ JavaScript than we're used to. Raw arrays are iterable _and_ they can be accessed via key. Microstate arrays are only iterable, so rather than being added magic, it's just a reduction in API. `Symbol.iterator` means that microstate arrays will work with React children, it will work with an Ember `{{#each}}`, and it will work with angular `ngFor`  without _zero_ need for adapters. That's really powerful.

I'd also add that the reduction in API surface to array access has actually improved my code because I'm forced to think in terms of list comprehensions rather than fiddling with individual members at their indices. Ironically, by allowing less, it makes the level at which you operate necessarily higher order.
